name: BR-ND
favicon: null
layout_spectrum: 0.75416
typography_spectrum: 0.13026
title: Emotive Transformers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#550000'
    - '#cc0066'
    - '#ff0055'
    - '#000000'
    - '#330000'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
