name: BR-ND
favicon: null
layout_spectrum: 0.14982404001057148
typography_spectrum: 0.6845054135192186
title: Emotive Transformers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8009676244109869
  lightness: 0.21251549944281578
  saturation: 0.4031338021159172
  rhythmicContrast: 0.30662238085642457
purpose: []
